logging:
    level:
        com:
            mockapi: TRACE
        web: INFO
spring:
    application:
        name: MockServer
    data:
        mongodb:
            uri: mongodb://localhost:27017/mockDB
    mvc:
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp
